name: ESLint and Prettier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  eslint:

    name: ESLint node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 16 ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    -
      name: Install npm dependencies
      run: npm install
    -
      name: Run ESLint
      run: npm run lint

  prettier:

    name: Prettier node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 16 ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    -
      name: Install npm dependencies
      run: npm install
    -
      name: Run Prettier
      run: npm run prettier
