name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install dependencies
      run: |
          sudo apt update
          sudo apt install python3 build-essential gobject-introspection liblightdm-gobject-1-dev libgirepository1.0-dev libcairo2-dev libxcb1-dev libx11-dev
          sudo apt install dpkg
    -
      name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: npm
    -
      name: Install npm dependencies
      run: npm install
    -
      name: Build nody-greeter
      run: npm run build
    -
      name: Build deb package
      run: |
        cd build/
        cp -r DEBIAN/ unpacked/
        dpkg-deb --root-owner-group --build unpacked "nody-greeter.deb"
        dpkg --info "./nody-greeter.deb"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/nody-greeter.deb
        asset_name: nody-greeter-$tag.deb
        tag: ${{ github.ref }}
        overwrite: true
